### ISSUE TITLE
Provide a docker image to run carbonifer

### ISSUE THREAD

**Issue by Joffref** [carboniferio/carbonifer#44]
**Is your feature request related to a problem? Please describe.**
As a carbonifer user, I would be able to run carbonifer in my CI/CD pipeline.
As a carbonifer contributor, I would be able to test it in a bundled environment. 

**Describe the solution you'd like**
To do so, I need a Docker image.

**Describe alternatives you've considered**
Use the CLI directly but it doesn't fit the contributor perspective.

**Comment by obierlaire** [comment]
Good idea!
