### ISSUE TITLE
Binary should include default config

### ISSUE THREAD

**Issue by obierlaire** [carboniferio/carbonifer#46]
**Describe the bug**
Currently, it reads config from `internal/utils/defaults.yaml` then `~/.carbonifer/config.yaml` then `./.carbonifer/config.yaml`. When user runs it from source (`go run main.go ... `) it's working well and finds `internal/utils/defaults.yaml`, but when we run the binary from elsewhere, it's does not find the `defaults.yaml` config, and fails unless there is a `~/.carbonifer/config.yaml`:

**To Reproduce**
```
$ go install go install github.com/carboniferio/carbonifer@latest
$ cd path/to/some/terraform/project
$ carbonifer plan .
```
Then we get this error message: 

```
PANI[0000] Config File "config" Not Found in "[$HOME/.carbonifer /etc/carbonifer /path/to/some/terraform/project/.carbonifer]" 
panic: (*logrus.Entry) 0x14000197ab0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x14000197a40, 0x0, {0x140000ee420, 0xa2})
        /Users/olivier/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x318
github.com/sirupsen/logrus.(*Entry).Log(0x14000197a40, 0x0, {0x1400011dc80, 0x1, 0x1})
        /Users/olivier/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x7c
github.com/sirupsen/logrus.(*Logger).Log(0x140000ca000, 0x0, {0x1400011dc80, 0x1, 0x1})
        /Users/olivier/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/logger.go:204 +0x70
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /Users/olivier/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/logger.go:253
github.com/sirupsen/logrus.Panic(...)
        /Users/olivier/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/exported.go:129
github.com/carboniferio/carbonifer/cmd.initConfig()
        /Users/olivier/go/pkg/mod/github.com/carboniferio/carbonifer@v0.2.0/cmd/root.go:88 +0x288
```

**Expected behavior**
Have default config value included in the binary and should not fail if no config file exists.

**Comment by Joffref** [comment]
Nice one ! I saw the same behavior. I think you can end up setting default values thanks to `viper.SetDefault()`.

**Comment by obierlaire** [comment]
> Nice one ! I saw the same behavior. I think you can end up setting default values thanks to `viper.SetDefault()`.

Yes, that's what I'm doing, but `viper.SetDefault()` takes only key/values and not a yaml structure. So instead of setting everything one by one, I preferred loading a yaml file and iterating over each key/value. But there is still a problem because this will fail if this file does not exist! So I think the best is to embed this yaml file at build time.

**Comment by Joffref** [comment]
What do you mean there ?
>  but `viper.SetDefault()` takes only key/values and not a yaml structure. So instead of setting everything one by one, I preferred loading a yaml file and iterating over each key/value.  

Do you have any example ?

**Comment by obierlaire** [comment]
> What do you mean there ?
Because `viper.SetDefault()` does not take a struct or a yaml file as parameter, I worked around it by reading a yaml file, iterate over all key/values and for each iteration, call `viper.SetDefault()`.

> Do you have any example ?
https://github.com/carboniferio/carbonifer/blob/main/internal/utils/config.go#L32
