### ISSUE TITLE
"panic: interface conversion: interface {} is *tfjson.unknownConstantValue, not string"

### ISSUE THREAD

**Issue by Wolfsrudel** [carboniferio/carbonifer#75]
**Describe the bug**
"panic: interface conversion: interface {} is *tfjson.unknownConstantValue, not string"

**To Reproduce**
1. Generate plan file
2. Run carbonifer with plan file

**Expected behavior**
carbonifer should not exit with an error.

**Screenshots**
-

**Environment:**
 - OS: alpine 3.18
 - Terraform version: 1.4.6
 - Carbonifer Version: 0.3.0

**Additional context**
Full error stack/ output
```
panic: interface conversion: interface {} is *tfjson.unknownConstantValue, not string
goroutine 1 [running]:
github.com/carboniferio/carbonifer/internal/terraform.GetResources(0xc0001c8d80)
	/home/runner/work/carbonifer/carbonifer/internal/terraform/resources.go:81 +0xf74
github.com/carboniferio/carbonifer/cmd.glob..func1(0xeda900?, {0xc00010dcb0, 0x1, 0x1?})
	/home/runner/work/carbonifer/carbonifer/cmd/plan.go:63 +0x1df
github.com/spf13/cobra.(*Command).execute(0xeda900, {0xc00010dc80, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xedabe0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/carboniferio/carbonifer/cmd.Execute()
	/home/runner/work/carbonifer/carbonifer/cmd/root.go:[42](https://git.tech.rz.db.de/dna/pipelines/accounts/iat/state-bucket/-/jobs/135687547#L42) +0x25
main.main()
	/home/runner/work/carbonifer/carbonifer/main.go:24 +0x53
```
First google-ing around gave me this one:
```
https://github.com/hashicorp/terraform-provider-aws/issues/10528
```
Dunno if it's related.

**Comment by obierlaire** [comment]
Hey @Wolfsrudel thanks for reporting ❤️ 

I think I managed to reproduce it, it might be because of the way you set the *default* region.
Just to confirm did you set it with a variable? like: 

```
provider "aws" {
  region = var.region
}

variable "region" {
  default = "eu-west-3"
}
```

If yes, I'll come up with a fix soon. In the meantime, you could work around it by hard coding it in `provider "was" {` block.

The way we are fetching the default region needs improvements (#58), but I think I'll come up with a fix for this particular problem soon (this week maybe)

**Comment by Wolfsrudel** [comment]
Yes, I can confirm that we are using a variable for setting the region dynamically. :)

**Comment by Wolfsrudel** [comment]
No, unfortunately it is not working at the moment. I get the following error message:
> "Error getting region from provider config no value found for expression"

But I also believe that I use a constellation that has not yet been considered when setting the region:

```
provider "aws" {
   region = module.globals.common_region
}
```
I get the input for the region from an output of another module.

Does this help with troubleshooting?

**Comment by obierlaire** [comment]
Sorry to read that @Wolfsrudel 

OK, dealing with called modules is much more complex, as there can be modules calling modules... And at this stage of this project, it was not planned. 

However, I think I managed to adapt the way we are resolving references to take into account modules. I hope this v0.3.2 (https://github.com/carboniferio/carbonifer/releases/tag/v0.3.2) will fix your issue.

**Comment by Wolfsrudel** [comment]
Unfortunately I keep getting an error. I have the relevant part (I suspect) from the plan file here:

```json
// snip
  "configuration": {
    "provider_config": {
      "aws": {
        "name": "aws",
        "full_name": "registry.terraform.io/hashicorp/aws",
        "version_constraint": "~\u003e 5.0",
        "expressions": {
          "default_tags": [
            {
              "tags": {
                "references": [
                  // [REDACTED]
                ]
              }
            }
          ],
          "region": {
            "references": [
              "module.globals.common_region",
              "module.globals"
            ]
          }
        }
      },
    }
  }
// snap
```

**Comment by obierlaire** [comment]
I tested sucessfully with the following :
```
configuration": {
    "provider_config": {
      "aws": {
        "name": "aws",
        "full_name": "registry.terraform.io/hashicorp/aws",
        "expressions": {
          "region": {
            "references": [
              "module.globals.common_region",
              "module.globals"
            ]
          }
        }
      },
```

Later, my module_calls look like: 
```
"module_calls": {
        "globals": {
          "source": "../aws_globals",
          "module": {
            "outputs": {
              "common_region": {
                "expression": {
                  "references": [
                    "var.region"
                  ]
                },
                "description": "The common AWS region used across modules"
              }
            },
            "variables": {
              "region": {
                "default": "eu-west-3"
              }
            }
          }
        }
      },
```
Can you share your module_cales defining how to resolve `common_region`
Also, are you sure you are using v0.3.2 ?

**Comment by Wolfsrudel** [comment]
I'll take a look after the weekend.

What I can already tell is that this is a perfectly normal module call. But the 'source' is a git repo. But that shouldn't be the deciding factor.

I also check the version.

I may have expressed myself incorrectly: I no longer get the error from the beginning, but I get the message that the 'region' is not set.

In any case, thanks in advance for the massive effort. :)

**Comment by Wolfsrudel** [comment]
Output of pipeline job:
```
$ carbonifer --version
carbonifer version 0.3.2
$ carbonifer plan ${TF_PLAN_FILE_JSON}
time="2023-06-26T06:16:41Z" level=fatal msg="Error getting region from provider config no value found for expression"
```
Module call
```terraform
module "tagging" {
  source = "git::https://<my-private-git-url>/tagging.git?ref=v0.2.0"
  
  [REDACTED: some inputs here]
}
```
providers.tf
```terraform
provider "aws" {
  region = module.globals.common_region
}
```
globals/output.tf
```terraform
output "common_region" {
  value = local.common_region
}
```
globals/locals.tf
```terraform
locals {
  common_region = "eu-central-1"
}
```

**Comment by obierlaire** [comment]
The problem is that `common_region` is declared as `locals` and terraform plan does not include `locals` variables (they should be resolved during `terraform apply`). Which is a bit annoying...
But, for already set `locals` variables (your case), terraform console manages to get them. 

So, for this case, with [v0.3.3](https://github.com/carboniferio/carbonifer/releases/tag/v0.3.3) carbonifer will now resolve local variables by calling `terraform console`

I hope this time this will solve this issue!

**Comment by Wolfsrudel** [comment]
You rock!

![image](https://github.com/carboniferio/carbonifer/assets/1692654/958c9098-e627-4255-a93d-4c2dcada95e6)

**Comment by Wolfsrudel** [comment]
Closing this issue.
